<% if (it.runtime.name === "deno") { -%>
name: Format Deno
on:
  pull_request:
    paths:
      - '**.js'
      - '**.ts'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno fmt --check $(find . -iname "*.[j|t]s")
<% } -%>