<% if (it.runtime.name === "deno") { -%>
name: Lint Deno
on:
  pull_request:
    paths:
      - '**.js'
      - '**.ts'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno lint --unstable
<% } else if (it.runtime.name === "node") { -%>
name: Lint JavaScript
on:
  pull_request:
    paths:
      - '**.js'
      - '**.ts'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '<%= it.runtime.version %>'
          cache: '<%= it.packageManager.name %>'

      <%_ let installCmd; let runPrefix; let globalInstall; -%>
      <%_ if (it.packageManager.name === "npm") { -%>
        <%_ installCmd = "npm ci" %>
        <%_ runPrefix = "npx eslint" %>
        <%_ globalInstall = "npm install -g eslint" %>
      <%_ } else { -%>
        <%_ installCmd = "yarn" %>
        <%_ runPrefix = "yarn eslint" %>
        <%_ globalInstall = "yarn global add eslint" %>
      <% } -%>

      - run: <%= installCmd %>
      <%_ if (it.linter.name === "eslint" && it.linter.hasIgnoreFile) { %>
      - run: <%= runPrefix %> --ext .js --ext .ts .
      <%_ } else if (it.linter.name === "eslint") { -%>
      - run: <%= runPrefix %> --ext .js --ext .ts --ignore-path .gitignore .
      <%_ } else { -%>
      - run: <%= globalInstall %>
      - run: <%= runPrefix %> --no-eslintrc --ext .js --ext .ts .
      <% } -%>
<% } -%>
