name: Format Python
on:
  pull_request:
    paths:
      - "**.py"
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: <%= it.version %>
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install <%= it.pythonPackageManager.name %>
          <%= it.pythonPackageManager.dependenciesCommand %>

      <%_ if (!it.blackFormatter.hasBlack) { %>
      - name: Install black
        run: pip install black
      <%_ } -%>

      - run: <%= it.pythonPackageManager.runCommand %> black . --check

      <%_ if (!it.isortFormatter.hasIsort) { %>
      - name: Install Isort
        run: pip install isort
      <%_ } -%>

      - run: <%= it.pythonPackageManager.runCommand %> isort . --check-only
