name: Lint Python
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: <%= it.version %>
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install <%= it.pythonPackageManager.name %>
          <%= it.pythonPackageManager.dependenciesCommand %>

        <%_ if (!it.flake8Linter.hasFlake8) { %>
      - name: Install Flake8
        run: pip install flake8
      <%_ } -%>

      - run: <%= it.pythonPackageManager.runCommand %> flake8
